execute pathogen#infect()

filetype on
filetype plugin on
filetype indent on

syntax enable

if has('win32')
  set guifont=Ubuntu\ Mono\ derivative\ Powerline:h21   " Win32
elseif has('gui_macvim')
  set guifont=Ubuntu\ Mono\ derivative\ Powerline:h21   " OSX
  set termguicolors
  " colorscheme github
else
  set guifont=Ubuntu\ Mono\ derivative\ Powerline:h21  " Linux
endif

set nocompatible
set encoding=utf-8
set title
set number
set visualbell                      " no beeping
set incsearch                       " Makes search act like search in modern browsers
set hlsearch                        " Highlight search results
set linespace=6
set autoread
set nobackup                        " Don't make a backup before overwriting a file
set nowritebackup                   " And again
set noswapfile                      " Use an SCM instead of swap files
set backspace=indent,eol,start      " http://vim.wikia.com/wiki/Backspace_and_delete_problems
set ts=4
set expandtab
set copyindent                      " copy the previous indentation on autoindenting
set shiftround                      " use multiple of shiftwidth when indenting with '<' and '>'
set showmatch                       " set show matching parenthesis
set autoindent
set laststatus=2                    " lines of status
set cursorline
set guioptions=aAce
set clipboard=unnamed
set listchars=tab:>-
set cmdheight=2

retab

vmap <Tab> >gva
vmap <S-Tab> <gv
" format JSON
map <leader>j !python -m json.tool<CR>
map <C-n> :NERDTreeToggle<CR>
map <C-l> gt
map <C-h> gT

" ctrlp
let g:ctrlp_map                 = '<leader>t'
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_custom_ignore       = '\v[\/](node_modules|target|dist|vendor)|(\.(swp|ico|git|DS_Store))$'

let g:airline_powerline_fonts      = 1
let g:airline_theme                = 'github'

let g:gitgutter_sign_column_always = 1
let g:gitgutter_enabled            = 1
let g:gitgutter_signs              = 1

let g:nerdtree_tabs_open_on_console_startup = 0
let g:nerdtree_tabs_open_on_new_tab         = 1
let NERDTreeShowHidden                      = 1

autocmd Filetype html setlocal ts=2 sts=2 sw=2
autocmd Filetype twig setlocal ts=2 sts=2 sw=2
autocmd Filetype javascript setlocal ts=2 sts=2 sw=2
autocmd FileType json setlocal tabstop=2 softtabstop=2 shiftwidth=2
autocmd Filetype php setlocal ts=4 sts=4 sw=4
autocmd Filetype yaml setlocal ts=4 sts=4 sw=4
autocmd FileType css setlocal tabstop=2 softtabstop=2 shiftwidth=2
autocmd FileType scss setlocal tabstop=2 softtabstop=2 shiftwidth=2
