execute pathogen#infect()

filetype on
syntax on
filetype plugin indent on

if has('win32')
  set guifont=Ubuntu\ Mono\ derivative\ Powerline:h21   " Win32
elseif has('gui_macvim')
  set guifont=JetBrains\ Mono:h17   " OSX
  set termguicolors
  set columnspace=-1
else
  set guifont=Ubuntu\ Mono\ derivative\ Powerline:h21  " Linux
endif

" set background=dark

set nocompatible
set encoding=utf-8
set termencoding=utf-8
set title
set number
set visualbell                      " no beeping
set incsearch                       " Makes search act like search in modern browsers
set hlsearch                        " Highlight search results
set linespace=8
set autoread
set nobackup                        " Don't make a backup before overwriting a file
set nowritebackup                   " And again
set noswapfile                      " Use an SCM instead of swap files
set backspace=indent,eol,start      " http://vim.wikia.com/wiki/Backspace_and_delete_problems
set ts=4
set expandtab
set copyindent                      " copy the previous indentation on autoindenting
set shiftround                      " use multiple of shiftwidth when indenting with '<' and '>'
set showmatch                       " set show matching parenthesis
set autoindent
set laststatus=2                    " lines of status
set cursorline
set guioptions+=e
set clipboard=unnamed
set listchars=tab:>-
set cmdheight=1
set signcolumn=yes
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set runtimepath^=~/.vim/bundle/ctrlp.vim

retab

vmap <Tab> >gva
vmap <S-Tab> <gv
" format JSON
map <leader>j !python -m json.tool<CR>

nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" Alternative tab navigation (cmd+number)
map <D-1> 1gt  
map <D-2> 2gt  
map <D-3> 3gt
map <D-4> 4gt
map <D-5> 5gt
map <D-6> 6gt
map <D-7> 7gt
map <D-8> 8gt
map <D-9> 9gt

let g:autotagTagsFile=".tags"

" ctrlp
let g:ctrlp_map                 = '<leader>t'
let g:ctrlp_cmd                 = 'CtrlP'
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_custom_ignore       = '\v[\/](node_modules|target|dist|vendor)|(\.(swp|ico|git|DS_Store))$'
let g:ctrlp_user_command        = ['.git', 'cd %s && git ls-files -co --exclude-standard']

"let g:gitgutter_sign_column_always = 1
let g:airline_theme                = 'solarized'
let g:airline_powerline_fonts      = 1
let g:gitgutter_enabled            = 1
let g:gitgutter_signs              = 1

autocmd Filetype html setlocal ts=2 sts=2 sw=2
autocmd Filetype twig setlocal ts=2 sts=2 sw=2
autocmd Filetype javascript setlocal ts=2 sts=2 sw=2
autocmd FileType json setlocal tabstop=2 softtabstop=2 shiftwidth=2
autocmd Filetype php setlocal ts=4 sts=4 sw=4
autocmd Filetype yaml setlocal ts=4 sts=4 sw=4
autocmd FileType css setlocal tabstop=2 softtabstop=2 shiftwidth=2
autocmd FileType scss setlocal tabstop=2 softtabstop=2 shiftwidth=2
